services:
  notes:
    image: notes:latest
    ports:
      - 8080:8080
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true


  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
